# Generated by Django 2.0.1 on 2018-01-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='rating',
            field=models.CharField(default='some string', max_length=400),
        ),
    ]
