# Generated by Django 2.0.1 on 2018-02-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_recognition', '0003_question_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
