# Generated by Django 2.0.1 on 2018-02-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_recognition', '0004_auto_20180202_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('keyAPI', models.CharField(max_length=200)),
                ('pathTrainingDataSet', models.CharField(max_length=1000, null=True)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
