# Generated by Django 2.0.1 on 2018-02-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_recognition', '0005_auto_20180207_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customerr'},
        ),
    ]
