# Generated by Django 2.0.1 on 2018-02-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_recognition', '0006_auto_20180207_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customerr',
        ),
    ]
