# Generated by Django 2.0.1 on 2018-02-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker_recognition', '0007_auto_20180207_1257'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
